options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests"]

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/bihar-service
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/bihar-service

images:
  - gcr.io/$PROJECT_ID/bihar-service
