package com.bihar.seva.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

import java.time.LocalDateTime;

/**
 * Auto-generated Categories from Services
 * Created automatically when providers add services
 */
@Data
@Document(collection = "categories")
public class Category {
    @Id
    private String id;
    
    @Indexed(unique = true)
    private String name; // Category name (normalized)
    
    private String displayName; // User-friendly name
    private String description;
    private String icon; // Icon emoji or URL
    
    // Auto-generated stats
    private Integer serviceCount = 0; // Number of services in this category
    private Integer providerCount = 0; // Number of providers offering this category
    
    // Status
    private Boolean isActive = true;
    private Boolean isAutoGenerated = true; // true if auto-generated, false if admin created
    
    // Timestamps
    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt = LocalDateTime.now();
    
    // Popularity
    private Integer searchCount = 0; // How many times searched
    private Integer bookingCount = 0; // Total bookings in this category
}
