// Bihar Cities and Districts
export const BIHAR_CITIES = [
  // Major Cities
  'Patna',
  'Gaya',
  'Bhagalpur',
  'Muzaffarpur',
  'Darbhanga',
  'Purnia',
  'Bihar Sharif',
  'Arrah',
  'Begusarai',
  'Katihar',
  'Munger',
  'Chhapra',
  'Saharsa',
  'Sasaram',
  'Hajipur',
  'Dehri',
  'Siwan',
  'Motihari',
  'Nawada',
  'Bagaha',
  'Buxar',
  'Kishanganj',
  'Sitamarhi',
  'Jamalpur',
  'Jehanabad',
  'Aurangabad',
  
  // All Districts
  'Araria',
  'Arwal',
  'Banka',
  'Bhojpur',
  'Buxar',
  'East Champaran',
  'West Champaran',
  'Gopalganj',
  'Jamui',
  'Kaimur',
  'Khagaria',
  'Lakhisarai',
  'Madhepura',
  'Madhubani',
  'Nalanda',
  'Rohtas',
  'Samastipur',
  'Saran',
  'Sheikhpura',
  'Sheohar',
  'Supaul',
  'Vaishali',
];

export const BIHAR_DISTRICTS = [
  { name: 'Araria', division: 'Purnia' },
  { name: 'Arwal', division: 'Magadh' },
  { name: 'Aurangabad', division: 'Magadh' },
  { name: 'Banka', division: 'Bhagalpur' },
  { name: 'Begusarai', division: 'Munger' },
  { name: 'Bhagalpur', division: 'Bhagalpur' },
  { name: 'Bhojpur', division: 'Patna' },
  { name: 'Buxar', division: 'Patna' },
  { name: 'Darbhanga', division: 'Darbhanga' },
  { name: 'East Champaran', division: 'Tirhut' },
  { name: 'Gaya', division: 'Magadh' },
  { name: 'Gopalganj', division: 'Saran' },
  { name: 'Jamui', division: 'Munger' },
  { name: 'Jehanabad', division: 'Magadh' },
  { name: 'Kaimur', division: 'Patna' },
  { name: 'Katihar', division: 'Purnia' },
  { name: 'Khagaria', division: 'Munger' },
  { name: 'Kishanganj', division: 'Purnia' },
  { name: 'Lakhisarai', division: 'Munger' },
  { name: 'Madhepura', division: 'Kosi' },
  { name: 'Madhubani', division: 'Darbhanga' },
  { name: 'Munger', division: 'Munger' },
  { name: 'Muzaffarpur', division: 'Tirhut' },
  { name: 'Nalanda', division: 'Patna' },
  { name: 'Nawada', division: 'Magadh' },
  { name: 'Patna', division: 'Patna' },
  { name: 'Purnia', division: 'Purnia' },
  { name: 'Rohtas', division: 'Patna' },
  { name: 'Saharsa', division: 'Kosi' },
  { name: 'Samastipur', division: 'Darbhanga' },
  { name: 'Saran', division: 'Saran' },
  { name: 'Sheikhpura', division: 'Munger' },
  { name: 'Sheohar', division: 'Tirhut' },
  { name: 'Sitamarhi', division: 'Tirhut' },
  { name: 'Siwan', division: 'Saran' },
  { name: 'Supaul', division: 'Kosi' },
  { name: 'Vaishali', division: 'Tirhut' },
  { name: 'West Champaran', division: 'Tirhut' },
];

export const SERVICE_CATEGORIES = [
  { id: 1, name: 'Plumbing', icon: 'Plumbing', color: '#2196F3' },
  { id: 2, name: 'Electrical', icon: 'ElectricalServices', color: '#FFC107' },
  { id: 3, name: 'Cleaning', icon: 'CleaningServices', color: '#4CAF50' },
  { id: 4, name: 'Carpentry', icon: 'Carpenter', color: '#795548' },
  { id: 5, name: 'AC Repair', icon: 'AcUnit', color: '#00BCD4' },
  { id: 6, name: 'Painting', icon: 'FormatPaint', color: '#E91E63' },
  { id: 7, name: 'Appliance Repair', icon: 'LocalLaundryService', color: '#9C27B0' },
  { id: 8, name: 'Construction', icon: 'Construction', color: '#FF9800' },
  { id: 9, name: 'Gardening', icon: 'Yard', color: '#8BC34A' },
  { id: 10, name: 'Pest Control', icon: 'BugReport', color: '#F44336' },
  { id: 11, name: 'Home Security', icon: 'Security', color: '#607D8B' },
  { id: 12, name: 'Other Services', icon: 'Build', color: '#9E9E9E' },
];

export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  PROVIDER: 'PROVIDER',
  ADMIN: 'ADMIN',
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const KYC_STATUS = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

